/**
 * Problem: Given two strings s and t which consist of only lowercase letters.
 *          String t is generated by random shuffling string s and then add one
 *          more letter at a random position. Find the letter that was added in t.
 * Solve: map
 * Tips: no
 */
class Solution {
public:
    char findTheDifference(string s, string t) {
        int cnt[26] = {0};
        for (int i = 0; i < s.size(); ++i) {
            cnt[s[i]-'a']++;
        }

        for (int i = 0; i < t.size(); ++i) {
            cnt[t[i]-'a']--;
        }

        for (int i = 0; i < t.size(); ++i) {
            if (cnt[t[i]-'a'] != 0)
                return t[i];
        }

        return t[0];
    }
};
